---

- name: Elasticsearch | Operating System Configure
  include_tasks: os-config.yml
  tags:
    - os-configure
  when: elasticsearch_os_tuning

- name: Elasticsearch | Install for {{ install_mode }}
  import_tasks: "{{ install_mode }}/main.yml"

- name: Elasticsearch | Plugins
  import_tasks: plugins.yml
  tags:
    - elasticsearch_plugins

- name: Elasticsearch | Service
  import_tasks: service.yml
  tags:
    - elasticsearch_service
