---
- name: Elasticsearch | Include vars for {{ install_mode }}
  include_vars: vars/{{ install_mode }}.yml

- name: Elasticsearch | Install
  include_tasks: install.yml
  tags:
    - elasticsearch_install

- name: Elasticsearch | Install
  include_tasks: config.yml
  tags:
    - elasticsearch_configure
