---

- name: Restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: true
  when: elasticsearch_service_state != 'stopped' and not elasticsearch_service_output.changed
