---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: esmasterdata1
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.14-buster-openjdk-headless}
    groups:
      - elasticsearch
      - master_data_nodes
    privileged: false
    capabilities:
      - SYS_ADMIN
    published_ports:
      - 9201:9200
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    ulimits:
      - nofile:65535:65535
      - memlock:-1:-1
    stop_signal: 'RTMIN+3'
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
    networks:
      - name: es-network
        aliases:
          - esmasterdata1

  - name: esmasterdata2
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.14-buster-openjdk-headless}
    groups:
      - elasticsearch
      - master_data_nodes
    privileged: false
    capabilities:
      - SYS_ADMIN
    published_ports:
      - 9202:9200
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    ulimits:
      - nofile:65535:65535
      - memlock:-1:-1
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
    stop_signal: 'RTMIN+3'
    networks:
      - name: es-network
        aliases:
          - esmasterdata2

  - name: esmasterdata3
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.14-buster-openjdk-headless}
    groups:
      - elasticsearch
      - master_data_nodes
    privileged: false
    capabilities:
      - SYS_ADMIN
    published_ports:
      - 9203:9200
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
    ulimits:
      - nofile:65535:65535
      - memlock:-1:-1
    stop_signal: 'RTMIN+3'
    networks:
      - name: es-network
        aliases:
          - esmasterdata3

provisioner:
  name: ansible
  inventory:
    group_vars:
      elasticsearch:
        java_open_jdk_home: ${JAVA_JDK_HOME:-/usr/lib/jvm/java-11-openjdk-amd64}
        elasticsearch_version: ${ELASTICSEARCH_VERSION:-7.17.10}
        elasticsearch_platform: ${ELASTICSEARCH_PLATFORM:-linux-x86_64}
verifier:
  name: ansible
