---
- name: Elasticsearch | Installing dependencies
  apt:
    pkg: "{{ elasticsearch_required_libs }}"
    state: present

- name: Elasticsearch | Add gpg key
  apt_key:
    url: "{{ elasticsearch_gpg_key }}"
    state: present

- name: Elasticsearch | Add ppa repository
  apt_repository:
    repo: "{{ elasticsearch_ppa_source }}"
    state: present
    filename: elasticsearch

- name: Elasticsearch | Ensure Elasticsearch group
  group:
    name: "{{ elasticsearch_group }}"
    system: true
    gid: "{{ elasticsearch_gid | default(omit) }}"

- name: Elasticsearch | Ensure Elasticsearch user
  user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    shell: /bin/false
    system: true
    create_home: false
    uid: "{{ elasticsearch_uid | default(omit) }}"

- name: Elasticsearch | Gather package facts
  package_facts:
    manager: "auto"

- name: Elasticsearch | Install elasticsearch {{ elasticsearch_version }}
  apt:
    name: "elasticsearch={{ elasticsearch_version }}"
    update_cache: true
    state: "{{ elasticsearch_package_state }}"
    force: "{{ (elasticsearch_version not in ansible_facts.packages[item][0].version | default('')) | ternary(True, omit) }}"
  register: elasticsearch_deb_upgraded
  retries: 3
  until: elasticsearch_deb_upgraded is success
  notify:
    - Restart elasticsearch
